// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcj5d9ffHGQJhFn0G1wE-pgkKGpV-E6FE',
    appId: '1:60675749062:web:3654d3498bb012c57ed3c7',
    messagingSenderId: '60675749062',
    projectId: 'habittracker-1384f',
    authDomain: 'habittracker-1384f.firebaseapp.com',
    storageBucket: 'habittracker-1384f.appspot.com',
    measurementId: 'G-ZL7YLQ26K8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApwGjaR3Q9ukSx_z5pMkgi-kEky_XcbAI',
    appId: '1:60675749062:android:1814a0e64810de5a7ed3c7',
    messagingSenderId: '60675749062',
    projectId: 'habittracker-1384f',
    storageBucket: 'habittracker-1384f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG4WwalnFG4VCANapK39CnuDyrt6rXYSs',
    appId: '1:60675749062:ios:720731b1c116bf0b7ed3c7',
    messagingSenderId: '60675749062',
    projectId: 'habittracker-1384f',
    storageBucket: 'habittracker-1384f.appspot.com',
    iosClientId: '60675749062-u8bu1ap8tpljkhaa29fvc8invrlco0aa.apps.googleusercontent.com',
    iosBundleId: 'com.example.tracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG4WwalnFG4VCANapK39CnuDyrt6rXYSs',
    appId: '1:60675749062:ios:11e7871526a46adc7ed3c7',
    messagingSenderId: '60675749062',
    projectId: 'habittracker-1384f',
    storageBucket: 'habittracker-1384f.appspot.com',
    iosClientId: '60675749062-46scaekda5p6qi1mldgd4q7ffadvc9d0.apps.googleusercontent.com',
    iosBundleId: 'com.example.tracker.RunnerTests',
  );
}
